pub const BRONKO_VERSION: &str = env!("CARGO_PKG_VERSION");
pub const MIN_KMER_SIZE: usize = 15;
pub const DEFAULT_KMER_SIZE: usize = 21; //kmer size
pub const MAX_KMER_SIZE: usize = 31;
pub const MIN_KMER_COUNT: usize = 3; // minimum number of times a kmer must occur to be run through algorithm
pub const DEFAULT_MIN_AF: f64 = 0.03; // minimum allele frequency to be reported
pub const DEFAULT_NO_FILTER_ENDS: bool = false; //flag to not filter variants on the ends of sequences 
pub const DEFAULT_NO_STRAND_FILTER: bool = false; // do not use a strand filter
pub const DEFAULT_NO_STRAND_BALANCE_FILTER: bool = false; //do not filter variants with extremely unbalanced strands
pub const DEFAULT_STRAND_BALANCE_RATIO: f64 = 0.1; //percent of total depth that one strand must be under to be called extremely unbalanced
pub const DEFAULT_N_KMERS_PER_STRAND: usize = 2;  //number of kmers that are needed to support each strand to call a variant
pub const DEFAULT_MAX_STRAND_ODDS: f64 = 6.0; // Strand odds ratio that must be under
pub const DEFAULT_NOISE_MULTIPLIER: f64 = 1.5; //How much variant must be above baseline noise (with exponential increase below 1% (going up to + 0.3 higher))
pub const DEFAULT_TSV_PILEUP: bool = false; //print a pileup as well
pub const DEFAULT_ALIGNMENT: bool = false; // return an alignment
pub const DEFAULT_KEEP_KMER_INFO: bool = false; //also print out kmer counts (deleted by default)
pub const DEFAULT_N_FIXED: usize = 2;   //number of fixed bases in the kmer
pub const DEFAULT_USE_FULL_KMER: bool = false;  //use the full length of the kmer
pub const DEFAULT_MIN_DEPTH: usize = MIN_KMER_COUNT*100;
pub const DEFAULT_INDEX_OUTPUT: &str = "bronko";
pub const DEFAULT_OUT_FOLDER: &str = "bronko_output";